packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

catalog:
  typescript: ^5.6
  node: ^20.0
  "@types/node": ^20.0
  react: ^18.0
  "@types/react": ^18.0
  react-dom: ^18.0
  "@types/react-dom": ^18.0
  vite: ^6.0
  vitest: ^3.0
  tailwindcss: ^4.0
  "@tailwindcss/vite": ^4.0

